name: deploy client preview website
"on":
  pull_request

env:
  SITE_URL: ${{ secrets.SITE_URL }}
  GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
  GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
  BASE_URL: ${{ secrets.BASE_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
      - run: yarn install --immutable
      - run: yarn build
      - run: npx vercel build
      - run: npx vercel deploy --prebuilt
